In [ ]:
# Importing the most important library numpy
# Numpy is preffered over python lists since most of its implementations are faster (the functions are tied closer with hardware)
import numpy as np

### Run the following to grasp the basics of numpy

In [ ]:
# 1D array
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Array of zeros
zeros = np.zeros((2, 3))
print("Zeros Array:\n", zeros)

# Array of ones
ones = np.ones((3, 2))
print("Ones Array:\n", ones)

# Array with a range of values
range_arr = np.arange(0, 10, 2)
print("Range Array:", range_arr)

# Array with equally spaced values
linspace_arr = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_arr)

# Random array
random_arr = np.random.rand(3, 3)  # Uniform distribution
print("Random Array:\n", random_arr)


In [ ]:
# In a numpy array, all the elements must be homogenous (of the same data type)
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  # Dimensions
print("Size:", arr.size)  # Total number of elements
print("Data Type:", arr.dtype)  # Type of elements
print("Number of Dimensions:", arr.ndim)  # Number of dimensions

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print("Element at [0, 1]:", arr[0, 1])  # Row 0, Column 1

# Slicing
print("First row:", arr[0, :])  # All columns of the first row
print("First column:", arr[:, 0])  # All rows of the first column
print("Subarray:\n", arr[0:2, 1:3])  # Rows 0-1 and Columns 1-2

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

# Broadcasting
scalar = 2
print("Multiply by scalar:", arr1 * scalar)

# Mathematical functions
print("Square root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape
reshaped = arr.reshape((3, 2))
print("Reshaped Array:\n", reshaped)

# Transpose
transposed = arr.T
print("Transposed Array:\n", transposed)

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking
stacked = np.vstack((arr1, arr2))  # Vertical stack
print("Stacked Vertically:\n", stacked)

hstacked = np.hstack((arr1, arr2))  # Horizontal stack
print("Stacked Horizontally:", hstacked)

# Splitting
split = np.split(arr2, 3)  # Split into 3 parts
print("Split Array:", split)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Boolean indexing
even = arr[arr % 2 == 0]
print("Even Numbers:", even)
# Masking is a common technique used
print("Masking:", arr % 2 == 0)

# Filtering
filtered = arr[arr > 3]
print("Numbers greater than 3:", filtered)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

### Some assignment problems

In [1]:
import numpy as np

# 1. Create an array of 18 random elements and reshape to (3, 6)
arr = np.random.rand(18).reshape(3, 6)
print("Original array (3x6):\n", arr)

# 2. Add the array [0, 0, 2, 4, 5, 3] to each row
add_array = np.array([0, 0, 2, 4, 5, 3])
arr_added = arr + add_array
print("\nAfter adding [0, 0, 2, 4, 5, 3] to each row:\n", arr_added)

# 3. Reshape to (9, 2)
reshaped = arr_added.reshape(9, 2)
print("\nReshaped array (9x2):\n", reshaped)

# 4. Take transpose
transposed = reshaped.T
print("\nTransposed array (2x9):\n", transposed)

# 5. Find locations where all elements are greater than the mean
mean_value = np.mean(transposed)
print("\nMean of the array:", mean_value)

locations = np.where(transposed > mean_value)
print("\nLocations where elements are greater than the mean:")
print(locations)


Original array (3x6):
 [[0.44621198 0.41568453 0.31094607 0.47588527 0.65059115 0.80036283]
 [0.81957665 0.52421152 0.73124972 0.85729283 0.86077809 0.10303364]
 [0.34235912 0.09357635 0.39476075 0.6840115  0.71580386 0.14623209]]

After adding [0, 0, 2, 4, 5, 3] to each row:
 [[0.44621198 0.41568453 2.31094607 4.47588527 5.65059115 3.80036283]
 [0.81957665 0.52421152 2.73124972 4.85729283 5.86077809 3.10303364]
 [0.34235912 0.09357635 2.39476075 4.6840115  5.71580386 3.14623209]]

Reshaped array (9x2):
 [[0.44621198 0.41568453]
 [2.31094607 4.47588527]
 [5.65059115 3.80036283]
 [0.81957665 0.52421152]
 [2.73124972 4.85729283]
 [5.86077809 3.10303364]
 [0.34235912 0.09357635]
 [2.39476075 4.6840115 ]
 [5.71580386 3.14623209]]

Transposed array (2x9):
 [[0.44621198 2.31094607 5.65059115 0.81957665 2.73124972 5.86077809
  0.34235912 2.39476075 5.71580386]
 [0.41568453 4.47588527 3.80036283 0.52421152 4.85729283 3.10303364
  0.09357635 4.6840115  3.14623209]]

Mean of the array: 2.8540315

In [ ]:
# Assignment 2
'''
Create an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation
(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)
'''

In [2]:
import numpy as np

# 1. Create an array of length 20 from a Poisson distribution
poisson_data = np.random.poisson(lam=5, size=20)
print("Original Poisson data:\n", poisson_data)

# 2. Calculate mean and standard deviation
mean_val = np.mean(poisson_data)
std_val = np.std(poisson_data)

print("\nMean:", mean_val)
print("Standard Deviation:", std_val)

# 3. Center the data around the mean
centered_data = poisson_data - mean_val
print("\nCentered data:\n", centered_data)

# 4. Normalize by dividing by the standard deviation
normalized_data = centered_data / std_val
print("\nNormalized data:\n", normalized_data)


Original Poisson data:
 [9 5 8 5 4 3 4 3 4 6 4 6 2 7 5 5 3 5 5 4]

Mean: 4.85
Standard Deviation: 1.6815171720800237

Centered data:
 [ 4.15  0.15  3.15  0.15 -0.85 -1.85 -0.85 -1.85 -0.85  1.15 -0.85  1.15
 -2.85  2.15  0.15  0.15 -1.85  0.15  0.15 -0.85]

Normalized data:
 [ 2.46800929  0.08920516  1.87330826  0.08920516 -0.50549588 -1.10019691
 -0.50549588 -1.10019691 -0.50549588  0.68390619 -0.50549588  0.68390619
 -1.69489795  1.27860722  0.08920516  0.08920516 -1.10019691  0.08920516
  0.08920516 -0.50549588]
